AspUpdateAjax/AspUpdateAjax/Models/QuestionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AspUpdateAjax.Models
{
    public class QuestionViewModel
    {
        public long SessionID { get; set; }
        public String SessionName { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Please enter a value bigger than {1}")]
        public int SessionType { get; set; }
        [Required(ErrorMessage = "Please Enter question Name")]
        public string QuestionName { get; set; }
        public int QuestionOption { get; set; }
        public string Answer1 { get; set; }
        public string Answer2 { get; set; }
        public string Answer3 { get; set; }
        public string Answer4 { get; set; }
        public string Answer5 { get; set; }
        public int CorrectAnswer { get; set; }
    }
}

AspUpdateAjax/AspUpdateAjax/ViewModels/QuestionViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AspUpdateAjax.ViewModels
{
    public class QuestionViewModel
    {
        public long SessionID { get; set; }
        public String SessionName { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Please enter a value bigger than {1}")]
        public int SessionType { get; set; }
        [Required(ErrorMessage = "Please Enter question Name")]
        public string QuestionName { get; set; }
        public int QuestionOption { get; set; }
        public string Answer1 { get; set; }
        public string Answer2 { get; set; }
        public string Answer3 { get; set; }
        public string Answer4 { get; set; }
        public string Answer5 { get; set; }
        public int CorrectAnswer { get; set; }
    }
}

AspUpdateAjax/AspUpdateAjax/ViewModels/UserLoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AspUpdateAjax.ViewModels
{
    public class UserLoginViewModel
    {
        [Required(ErrorMessage = "Please enter your username")]
        [Display(Name = "UserName")]
        [MaxLength(50)]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Please enter your password")]
        [Display(Name = "Password")]
        [MaxLength(50)]
        public string Password { get; set; }
    } 
}

AspUpdateAjax/AspUpdateAjax/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AspUpdateAjax.ViewModels;

namespace AspUpdateAjax.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
       
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public String OnBeginRequest()
        {
            Session["QuestionViewModel"] = null;
            return "ok";
        }
        [HttpPost]
        public String RemoveRequest(string text)
        {
            // Session["QuestionViewModel"] = null;
            List<QuestionViewModel> questionViewModels = Session["QuestionViewModel"] as List<QuestionViewModel>;
            if (questionViewModels != null)
            {
               questionViewModels= questionViewModels.Where(x => !x.QuestionName.Contains(text.Trim())).ToList();
               Session["QuestionViewModel"] = questionViewModels;
            }
            return "OK";
        }
        

        [HttpPost]
        public PartialViewResult AddQuestions(QuestionViewModel model)
        {
            List<QuestionViewModel> questionViewModels = Session["QuestionViewModel"] as List<QuestionViewModel>;
            if (questionViewModels == null)
            {
                questionViewModels=new List<QuestionViewModel>();
            }
            else
            {
                questionViewModels = questionViewModels.Where(x => !x.QuestionName.Contains(model.QuestionName.Trim())).ToList();
            }
            questionViewModels.Add(model);
            Session["QuestionViewModel"] = questionViewModels;
            return PartialView("_QuestionPartial", questionViewModels);
        }

        [HttpPost]
        public ActionResult Save()
        {
            var questionViewModels = Session["QuestionViewModel"] as List<QuestionViewModel>;
            if (questionViewModels == null)
            {
                return Redirect("/Admin/Index");
            }
            return View();
        }
    }
}

AspUpdateAjax/AspUpdateAjax/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AspUpdateAjax.Models;

namespace AspUpdateAjax.Controllers
{
    public class HomeController : Controller
    {
       
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public String OnBeginRequest()
        {
            Session["QuestionViewModel"] = null;
            return "ok";
        }
        [HttpPost]
        public String RemoveRequest(string text)
        {
            // Session["QuestionViewModel"] = null;
            List<QuestionViewModel> questionViewModels = Session["QuestionViewModel"] as List<QuestionViewModel>;
            if (questionViewModels != null)
            {
               questionViewModels= questionViewModels.Where(x => !x.QuestionName.Contains(text.Trim())).ToList();
               Session["QuestionViewModel"] = questionViewModels;
            }
            return "OK";
        }
        

        [HttpPost]
        public PartialViewResult AddQuestions(QuestionViewModel model)
        {
            List<QuestionViewModel> questionViewModels = Session["QuestionViewModel"] as List<QuestionViewModel>;
            if (questionViewModels == null)
            {
                questionViewModels=new List<QuestionViewModel>();
            }
            else
            {
                questionViewModels = questionViewModels.Where(x => !x.QuestionName.Contains(model.QuestionName.Trim())).ToList();
            }
            questionViewModels.Add(model);
            Session["QuestionViewModel"] = questionViewModels;
            return PartialView("_QuestionPartial", questionViewModels);
        }

        [HttpPost]
        public ActionResult Save()
        {
            return View();
        }
    }
}

AspUpdateAjax/AspUpdateAjax/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using AspUpdateAjax.ViewModels;

namespace AspUpdateAjax.Controllers
{

    public class SecurityController : Controller
    {
        // GET: Security
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(UserLoginViewModel user)
        {
            // To acces data using LINQ
            // DataClassesDataContext mobjentity = new DataClassesDataContext();
            if (ModelState.IsValid)
            {
                int a = 0;
                if (user.UserName == "akash")
                {
                    FormsAuthentication.SetAuthCookie(user.UserName, true);
                    return Redirect("/Admin/Index");
                }

            }
            return View("Index");
        }
    }
}

AspUpdateAjax/AspUpdateAjax/Views/Admin/Index.cshtml
@model AspUpdateAjax.ViewModels.QuestionViewModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddCountries</title>
</head>
<body>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <link href="~/Content/alertify.core.css" rel="stylesheet" />
    <link href="~/Content/alertify.default.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/alertify.js"></script>
    <script type="text/javascript">

        $(function () {
            $("#Answer1,#Answer2,#Answer3,#Answer4,#Answer5").prop("disabled", true);
            $("#Answer1,#Answer2,#Answer3,#Answer4,#Answer5").val('');
            $.ajax({
                type: "POST",
                url: "/Admin/OnBeginRequest",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (result) {
                    console.log(result);
                }
            });
            $(document).on('click', '.actionButton', function (event) {
                //console.log(e);
                //console.log($(this).parent());
                //console.log($(this).closest('tr').index());

                var index = $(this).closest('tr').index();
                var table = document.getElementById('tblQuestionDetails');
                var text = table.rows[index].cells[0].innerHTML;
                var deletedRow = $(this).closest('tr');
                // alertify.alert(text);
                // confirm dialog
                alertify.confirm("Are you sure to remove question", function (e) {
                    if (e) {
                        // user clicked "ok"
                        deletedRow.remove();
                        $.ajax({
                            type: "POST",
                            url: "/Admin/RemoveRequest",
                            data: JSON.stringify({ 'text': text }),
                            contentType: "application/json; charset=utf-8",
                            dataType: "json",
                            success: function (result) {
                                console.log(result);
                                if (result == "OK") {
                                    deletedRow.remove();
                                } else {
                                    alert('Opsss some thing wrong contract with administrator');
                                }
                            }
                        });

                    } else {
                        // user clicked "cancel"
                        alert(text);
                    }
                });
                //  $(this).closest('tr').remove();
            });
            $('#questionOption').on('change', function (ee) {

                var optionNo = $('#questionOption').val();
                $("#Answer1,#Answer2,#Answer3,#Answer4,#Answer5").prop("disabled", true);
                $("#Answer1,#Answer2,#Answer3,#Answer4,#Answer5").val('');
                // alert(optionNo);

                if (optionNo == 1) {
                    $("#Answer1").removeAttr("disabled");

                } else if (optionNo == 2) {
                    $("#Answer1,#Answer2").removeAttr("disabled");
                }
                else if (optionNo == 3) {
                    $("#Answer1,#Answer2,#Answer3").removeAttr("disabled");
                }
                else if (optionNo == 4) {
                    $("#Answer1,#Answer2,#Answer3,#Answer4").removeAttr("disabled");
                }
                else if (optionNo == 5) {
                    $("#Answer1,#Answer2,#Answer3,#Answer4,#Answer5").removeAttr("disabled");
                } else {
                    alertify.alert('Select At least one question ');
                }


            });
            //correctAnswer
            $('#correctAnswer').on('change', function (ee) {
                var questionOptionNo = $('#questionOption').val();
                var correctAnswerNo = $('#correctAnswer').val();

                //  alert(correctAnswerNo);
                if (correctAnswerNo > questionOptionNo) {
                    alertify.alert('Correct Answer can not bigger than no of question');
                    // return false;
                }

            });
            $('input[type="submit"]').click(function () {
                //  alert('In submit button');
                var questionOptionNo = $('#questionOption').val();
                var correctAnswerNo = $('#correctAnswer').val();
                if (correctAnswerNo <= 0) {
                    alertify.alert('select correct answer');
                    return false;
                } else if (correctAnswerNo > questionOptionNo) {
                    alertify.alert('Correct Answer can not bigger than no of question');
                    return false;
                }
                // return false;//oks fine
            });

        });
        function OnBeginRequest() {
            console.log('On Begin');

        }
        function OnCompleteRequest() {
            console.log('On Completed');
        }
        function OnSuccessRequest() {
            console.log('On Success');
        }
        function OnFailureRequest() {
            console.log('On Failure');
        }
    </script>

    @{
        AjaxOptions options = new AjaxOptions();
        options.HttpMethod = "POST";
        options.OnBegin = "OnBeginRequest";
        options.OnSuccess = "OnSuccessRequest";
        options.OnComplete = "OnCompleteRequest";
        options.OnFailure = "OnFailureRequest";
        //  options.Confirm = "Do you want to Add Country ?";
        options.UpdateTargetId = "divResponse";
        options.InsertionMode = InsertionMode.Replace;
    }

    @using (Ajax.BeginForm("AddQuestions", "Admin", options))
    {
        @Html.ValidationSummary(true)
        <div class="container">
            <fieldset>
                <legend>Add Questions</legend>
                <div class="row form-group">
                    <div class="col-lg-2">Session Name:</div>

                    <div class="col-lg-6">
                        @Html.TextAreaFor(model => model.SessionName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.SessionName)
                    </div>
                </div>
                <br />
                <div class="row form-group">
                    <div class="col-lg-2">Session Name:</div>

                    <div class="col-lg-6">
                        <select id="sessionType" name="sessionType" class="form-control">
                            @*<option value="0">select</option>*@
                            <option value="1">Notice</option>
                            <option value="2">Quiz</option>
                        </select>
                        @Html.ValidationMessageFor(model => model.SessionType)
                    </div>
                </div>
                <br />

                <div class="row form-group">
                    <div class="col-lg-2">Enter Question Name:</div>

                    <div class="col-lg-6">
                        @Html.TextAreaFor(model => model.QuestionName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.QuestionName)
                    </div>
                </div>
                <br />
                <div class="row form-group">

                    <div class="col-lg-2">No of Answer</div>
                    <div class="col-lg-4">
                        <select id="questionOption" name="questionOption" class="form-control">
                            <option value="0">select Option</option>
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                            <option value="4">Four</option>
                            <option value="5">Five</option>
                        </select>

                    </div>

                </div>
                <br />

                <div class="row form-group">

                    <div class="col-lg-2">Answer1</div>
                    <div class="col-lg-4">@Html.TextBoxFor(model => model.Answer1, new { @class = "form-control" })</div>

                </div>
                <br />
                <div class="row form-group">

                    <div class="col-lg-2">Answer2</div>
                    <div class="col-lg-4">@Html.TextBoxFor(model => model.Answer2, new { @class = "form-control" })</div>

                </div>
                <br />
                <div class="row form-group">

                    <div class="col-lg-2">Answer3</div>
                    <div class="col-lg-4">@Html.TextBoxFor(model => model.Answer3, new { @class = "form-control" })</div>

                </div>
                <br />
                <div class="row form-group">

                    <div class="col-lg-2">Answer4</div>
                    <div class="col-lg-4">@Html.TextBoxFor(model => model.Answer4, new { @class = "form-control" })</div>

                </div>
                <br />
                <div class="row form-group">

                    <div class="col-lg-2">Answer5</div>
                    <div class="col-lg-4">@Html.TextBoxFor(model => model.Answer5, new { @class = "form-control" })</div>

                </div>
                <br />
                <div class="row form-group">

                    <div class="col-lg-2">Correct Answer</div>
                    <div class="col-lg-4">
                        <select id="correctAnswer" name="correctAnswer" class="form-control">
                            <option value="0">select Option</option>
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                            <option value="4">Four</option>
                            <option value="5">Five</option>
                        </select>

                    </div>

                </div>
                <hr />
                <div class="row">
                    <div class="col-lg-1"><input type="submit" value="Add Question" class="btn btn-success" /></div>

                </div>
            </fieldset>
        </div>
    }

    <div class="container">
        <div id="divResponse">
        </div>
    </div>
    <br/>
    <br/>
    @using (@Html.BeginForm("Save", "Admin", FormMethod.Post))
    {
        <div class="container">
            <div class="row">
                <button type="submit" class="btn btn-info">Submit</button>  
            </div>
            
        </div>
    }

</body>
</html>

AspUpdateAjax/AspUpdateAjax/Views/Admin/_QuestionPartial.cshtml
@model IEnumerable<AspUpdateAjax.ViewModels.QuestionViewModel>
<div class="table-responsive">
    <table id="tblQuestionDetails" class="table table-bordered ">
        <tr class="text-danger">
            <th>@Html.DisplayNameFor(model => model.QuestionName)</th>
            <th>@Html.DisplayNameFor(model => model.CorrectAnswer)</th>
            <th>@Html.DisplayNameFor(model => model.Answer1)</th>
            <th>@Html.DisplayNameFor(model => model.Answer2)</th>
            <th>@Html.DisplayNameFor(model => model.Answer3)</th>
            <th>@Html.DisplayNameFor(model => model.Answer4)</th>
            <th>@Html.DisplayNameFor(model => model.Answer5)</th>

        </tr>

        @foreach (var item in Model)
        {
            <tr class="text-info">
                <td> @Html.DisplayFor(modelItem => item.QuestionName)</td>
                <td> @Html.DisplayFor(modelItem => item.CorrectAnswer)</td>
                <td>@Html.DisplayFor(modelItem => item.Answer1)</td>
                <td>@Html.DisplayFor(modelItem => item.Answer2)</td>
                <td>@Html.DisplayFor(modelItem => item.Answer3)</td>
                <td>@Html.DisplayFor(modelItem => item.Answer4)</td>
                <td>@Html.DisplayFor(modelItem => item.Answer5)</td>
                <td>
                    <button class="btn btn-danger actionButton" type="button" id="btnRemove">Remove</button>
                </td>
            </tr>
        }
    </table>
</div>

AspUpdateAjax/AspUpdateAjax/Views/Home/Save.cshtml
@{
    ViewBag.Title = "Save";
}

<h2>Save</h2>
<div class="container">
    <h2>Question havebeen saved successfully</h2>
    <a href="/Home/Index">Home Page</a>
</div>

AspUpdateAjax/AspUpdateAjax/Views/Home/_QuestionPartial.cshtml
@model IEnumerable<AspUpdateAjax.Models.QuestionViewModel>
<div class="table-responsive">
    <table id="tblQuestionDetails" class="table table-bordered ">
        <tr class="text-danger">
            <th>@Html.DisplayNameFor(model => model.QuestionName)</th>
            <th>@Html.DisplayNameFor(model => model.CorrectAnswer)</th>
            <th>@Html.DisplayNameFor(model => model.Answer1)</th>
            <th>@Html.DisplayNameFor(model => model.Answer2)</th>
            <th>@Html.DisplayNameFor(model => model.Answer3)</th>
            <th>@Html.DisplayNameFor(model => model.Answer4)</th>
            <th>@Html.DisplayNameFor(model => model.Answer5)</th>

        </tr>

        @foreach (var item in Model)
        {
            <tr class="text-info">
                <td> @Html.DisplayFor(modelItem => item.QuestionName)</td>
                <td> @Html.DisplayFor(modelItem => item.CorrectAnswer)</td>
                <td>@Html.DisplayFor(modelItem => item.Answer1)</td>
                <td>@Html.DisplayFor(modelItem => item.Answer2)</td>
                <td>@Html.DisplayFor(modelItem => item.Answer3)</td>
                <td>@Html.DisplayFor(modelItem => item.Answer4)</td>
                <td>@Html.DisplayFor(modelItem => item.Answer5)</td>
                <td>
                    <button class="btn btn-danger actionButton" type="button" id="btnRemove">Remove</button>
                </td>
            </tr>
        }
    </table>
</div>

AspUpdateAjax/AspUpdateAjax/Views/Security/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@model AspUpdateAjax.ViewModels.UserLoginViewModel
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/main.css" rel="stylesheet" />
<link href="~/Content/alertify.core.css" rel="stylesheet" />
<link href="~/Content/alertify.default.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script src="~/Scripts/bootstrap.js"></script>
<script src="~/Scripts/alertify.js"></script>
@{
    ViewBag.Title = "User Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Login","Security",FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <div class="editor-label">
        @Html.LabelFor(m => m.UserName)
    </div>
    <div class="editor-field">
        @Html.TextBoxFor(m => m.UserName)
        @Html.ValidationMessageFor(m => m.UserName)
    </div>
    <div class="editor-label">
        @Html.LabelFor(m => m.Password)
    </div>
    <div class="editor-field">
        @Html.PasswordFor(m => m.Password)
        @Html.ValidationMessageFor(m => m.Password)
    </div>
    <p>
        <input type="submit" value="Log In" />
    </p>
    
}

AspUpdateAjax/AspUpdateAjax/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>